import type { Metadata, Viewport } from 'next';
import { UserContextProvider } from '@/hooks/UserContextProvider';
import {
  HanaBold,
  HanaCM,
  HanaHeavy,
  HanaLight,
  HanaMedium,
  HanaRegular,
} from './fonts/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Viewport 설정
 * 2026.01.22
 *
 * UserContext설정
 * 2026.01.26 seonukim
 */
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1, // 확대 방지
  userScalable: false, // 핀치 줌 방지
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${HanaLight.variable} ${HanaRegular.variable} ${HanaMedium.variable} ${HanaBold.variable} ${HanaHeavy.variable} ${HanaCM.variable}`}
    >
      <body
        className={`flex h-dvh w-screen items-center justify-center overflow-hidden bg-gray-100 antialiased`}
      >
        <UserContextProvider>
          <div className="scrollbar-hide h-full max-h-[852px] w-full max-w-[393px] overflow-y-auto rounded-4xl bg-white p-3 shadow-md">
            {children}
          </div>
        </UserContextProvider>
      </body>
    </html>
  );
}
