import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Viewport 설정
 * 2026.01.22
 */
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1, // 확대 방지
  userScalable: false, // 핀치 줌 방지
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 flex justify-center items-center h-dvh w-screen overflow-hidden`}
      >
        <div className="w-full max-w-[393px] max-h-[852px] h-full bg-white shadow-md overflow-y-auto scrollbar-hide rounded-4xl p-3">
        {children}
        </div>
      </body>
    </html>
  );
}
0